#!/usr/bin/env python3
"""
Nansen Daily Signal Brief
Runs daily at 10pm IST (16:30 UTC)
Captures smart money signals across 5 chains, commits to GitHub, sends Telegram summary
"""
import subprocess, json, datetime, os, sys

REPO_DIR = "/root/nansen-agent"
CHAINS = ["ethereum", "solana", "base", "arbitrum", "bnb"]
THRESHOLD_USD = 5000
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

def run_nansen(args):
    result = subprocess.run(["nansen"] + args, capture_output=True, text=True, timeout=45)
    return json.loads(result.stdout)

def get_signals():
    today = datetime.date.today().isoformat()
    buys, sells = [], []

    for chain in CHAINS:
        try:
            # Inflows (buys)
            data = run_nansen(["research", "smart-money", "netflow",
                               "--chain", chain, "--days", "7",
                               "--sort", "net_flow_7d_usd:desc", "--limit", "5"])
            if data.get("success"):
                for t in data["data"]["data"]:
                    flow = t.get("net_flow_7d_usd", 0)
                    if flow >= THRESHOLD_USD:
                        buys.append({
                            "date": today, "chain": chain,
                            "token": t["token_symbol"],
                            "token_address": t.get("token_address", ""),
                            "net_flow_7d_usd": flow,
                            "market_cap_usd": t.get("market_cap_usd", 0),
                            "trader_count": t.get("trader_count", 0),
                            "direction": "BUY",
                            "score_date": (datetime.date.today() + datetime.timedelta(days=30)).isoformat(),
                            "result": "PENDING"
                        })

            # Outflows (sells)
            data = run_nansen(["research", "smart-money", "netflow",
                               "--chain", chain, "--days", "7",
                               "--sort", "net_flow_7d_usd:asc", "--limit", "5"])
            if data.get("success"):
                for t in data["data"]["data"]:
                    flow = t.get("net_flow_7d_usd", 0)
                    if flow <= -THRESHOLD_USD:
                        sells.append({
                            "date": today, "chain": chain,
                            "token": t["token_symbol"],
                            "token_address": t.get("token_address", ""),
                            "net_flow_7d_usd": flow,
                            "market_cap_usd": t.get("market_cap_usd", 0),
                            "trader_count": t.get("trader_count", 0),
                            "direction": "SELL",
                            "score_date": (datetime.date.today() + datetime.timedelta(days=30)).isoformat(),
                            "result": "PENDING"
                        })
        except Exception as e:
            print(f"Error on {chain}: {e}", file=sys.stderr)

    return buys, sells

def format_report(buys, sells, today):
    lines = [f"# Smart Money Signal Report — {today}\n",
             "*Generated by OpenClaw AI agent | Nansen CLI*\n",
             f"*Score date: {(datetime.date.today() + datetime.timedelta(days=30)).isoformat()} (+30d)*\n\n---\n",
             f"## 🟢 BUY Signals ({len(buys)} total)\n",
             "| Token | Chain | 7d Inflow | Traders |",
             "|-------|-------|-----------|---------|"]
    for s in sorted(buys, key=lambda x: -x["net_flow_7d_usd"])[:15]:
        lines.append(f"| **{s['token']}** | {s['chain']} | +${s['net_flow_7d_usd']:,.0f} | {s['trader_count']} |")

    lines += [f"\n## 🔴 SELL Signals ({len(sells)} total)\n",
              "| Token | Chain | 7d Outflow | Traders |",
              "|-------|-------|------------|---------|"]
    for s in sorted(sells, key=lambda x: x["net_flow_7d_usd"])[:10]:
        lines.append(f"| **{s['token']}** | {s['chain']} | ${s['net_flow_7d_usd']:,.0f} | {s['trader_count']} |")

    return "\n".join(lines)

def format_telegram(buys, sells, today):
    top_buys = sorted(buys, key=lambda x: -x["net_flow_7d_usd"])[:5]
    top_sells = sorted(sells, key=lambda x: x["net_flow_7d_usd"])[:3]

    msg = f"🧠 *Smart Money Brief — {today}*\n\n"
    msg += "🟢 *Top Buys (7d)*\n"
    for s in top_buys:
        conviction = "🔥" if s["net_flow_7d_usd"] > 100000 else "•"
        msg += f"{conviction} *{s['token']}* ({s['chain']}): +${s['net_flow_7d_usd']:,.0f} | {s['trader_count']} wallets\n"

    msg += "\n🔴 *Top Exits (7d)*\n"
    for s in top_sells:
        msg += f"⚠️ *{s['token']}* ({s['chain']}): ${s['net_flow_7d_usd']:,.0f} | {s['trader_count']} wallets\n"

    msg += f"\n📊 {len(buys)} buy signals, {len(sells)} sell signals captured\n"
    msg += "📁 github.com/charlie-analytics/nansen-agent"
    return msg

def commit_and_push(today, buys, sells):
    all_signals = buys + sells
    os.makedirs(f"{REPO_DIR}/data", exist_ok=True)
    os.makedirs(f"{REPO_DIR}/reports", exist_ok=True)

    with open(f"{REPO_DIR}/data/signals-{today}.json", "w") as f:
        json.dump(all_signals, f, indent=2)

    report = format_report(buys, sells, today)
    with open(f"{REPO_DIR}/reports/{today}.md", "w") as f:
        f.write(report)

    subprocess.run(["git", "-C", REPO_DIR, "add", "-A"])
    subprocess.run(["git", "-C", REPO_DIR, "commit", "-m",
                    f"daily signals: {today} ({len(buys)} buys, {len(sells)} sells)"])
    subprocess.run(["git", "-C", REPO_DIR, "push", "origin", "main"])

if __name__ == "__main__":
    today = datetime.date.today().isoformat()
    print(f"Running signal capture for {today}...")
    buys, sells = get_signals()
    print(f"Captured: {len(buys)} buys, {len(sells)} sells")
    commit_and_push(today, buys, sells)
    # Print Telegram summary to stdout for the cron job to send
    print("---TELEGRAM---")
    print(format_telegram(buys, sells, today))
